[package]
name = "keepass"
version = "1.0.0"
authors = [ "Luis Hector Chavez <lhchavez@lhchavez.com>" ]

[dependencies]
base64 = "^0.11"
clap = "^2.33"
cursive = "^0.16"
cursive_tree_view = "^0.7"
regex = "^1.3"
flate2 = "^1.0"
rpassword = "^4.0"
rust-crypto = " ^0.2"
sxd-document = "^0.3"
